detection_node:
  ros__parameters:
    model_path: "models/yolov8n.onnx"
    conf_threshold: 0.25
    nms_threshold: 0.45
    use_cuda: true
    infer_queue_size: 2
    ort_intra_threads: 2
    ort_inter_threads: 1
